

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TRANSFORMERS_CACHE=/mnt/ebs_cache
      - CHROMA_DB_PATH=/mnt/chroma_data
    volumes:
      - .:/app
      - /mnt/ebs_cache:/mnt/ebs_cache
      - /mnt/chroma_data:/mnt/chroma_data
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    container_name: chat_scheduler
    env_file:
      - .env
    environment:
      - TRANSFORMERS_CACHE=/mnt/ebs_cache
      - CHROMA_DB_PATH=/mnt/chroma_data
    volumes:
      - .:/app
      - /mnt/ebs_cache:/mnt/ebs_cache
      - /mnt/chroma_data:/mnt/chroma_data
    restart: unless-stopped
